### ISSUE TITLE
[Legacy version] yaml-pro-consult-jump error: Wrong type argument: stringp, return

### ISSUE THREAD

**Issue by uqix** [zkry/yaml-pro#18]
* error msg: Error in minibuffer-exit-hook (consult--preview-minibuffer-exit): (wrong-type-argument stringp exit)
* yaml-pro-jump does work

**Comment by zkry** [comment]
Thanks for this report! I think a newer version of consult must have broken this feature. I've identified a way to get the same functionality using imenu which should provide the same functionality using the command `consult-imenu`. I'll plan on getting the imenu integration for `yaml-pro-mode` implemented.

**Comment by zkry** [comment]
imenu should be supported in the latest release. Definitely let me know if you have any other issues!
