### ISSUE TITLE
Feature request: show path of current line/symbol

### ISSUE THREAD

**Issue by uqix** [zkry/yaml-pro#19]

**Comment by zkry** [comment]
Hello! These is a feauter implemented for the tree-sitter version of yaml-pro that may be what you're looking for. By enabling `yaml-pro-ts-mode` as well as `eldoc-mode` you should be able to see the current path for the symbol. 

As for getting this to work for the legacy parser, I could implement such a feature, but it would be very slow as I don't think the YAML processor can parse a long document fast enough to update everytime the point moves.

**Comment by uqix** [comment]
Thanks for this awesome pkg, will try Emacs 29 and `yaml-pro-ts-mode` soon.
