### ISSUE TITLE
Feature support: yaml-pro-ts-down-level

### ISSUE THREAD

**Issue by uqix** [zkry/yaml-pro#37]
Similar to `yaml-pro-ts-up-level`, add `yaml-pro-ts-down-level` so that we can jump to the first child of the current key;
then with next/prev subtree, we can jump to anywhere which is so handy with repeat-map.

**Comment by zkry** [comment]
I like the idea. I'll work on getting this in 👍

**Comment by zkry** [comment]
Thanks, should be good now in the latest master.
