### ISSUE TITLE
Define sentences so M-e / M-a work better

### ISSUE THREAD

**Issue by nullishamy** [zkry/yaml-pro#69]
Hello

Love the features you provide here! One issue: when trying to jump by sentence (M-e etc), there is no defined sentence boundary so emacs defaults to paragraph boundaries (newlines). 

In some types of documents, there is little / no newlines so this ends up jumping more than desired. Is there a solution that allows me to jump by a more sensible amount? 

Would not mind rebinding these binds for YAML mode, just couldn't figure out the correct calls / combination to have a pleasant experience from what docs I read.

Thanks

**Comment by zkry** [comment]
Hey! I can definitely rebind these keys with a new function. It currently has the `yaml-pro-ts-next-subtree` and `yaml-pro-ts-prev-subtree` for linear movement. I'm trying to think of something that would be good for M-e/M-a but nothing obvious comes to mind.

Is there anything analogous in any other mode that uses these bindings that you can think of. Org-mode for example has a function called `org-forward-sentence` which is a bit more complex than the paragraph moving commands. 

Like, maybe this command can act like forward sentence in a string, but outside, it can like traverse leaf nodes.

**Comment by nullishamy** [comment]
Yeah, next-subtree does work well however it won't go into the tree if it's the last in the document (even if that tree may be very big). We'd need some middle ground where it will go into the tree if it is large but skip it if it is smaller.

**Comment by zkry** [comment]
ok, I implemented new yaml-pro-ts-forward-sentence and backward-sentence functions, bounded by default to <kbd>M-a</kbd> and <kbd>M-e</kbd>. Let me know if they don't behave as you'd expect and I can modify them.

**Comment by nullishamy** [comment]
Works great! Only problem I have is that when at the very end of the document, `M-e` seems to hang / take a very long time to resolve (ie trying to jump further than the end of the document)

**Comment by zkry** [comment]
Oh, thanks for pointing that out. It should be fixed now in the latest release.

**Comment by nullishamy** [comment]
Yep, all working now, thanks for your work!
